language: ruby

cache: bundler

rvm:
  - 2.7

branches:
  only:
    - src

before script:

install:
  - gem install jekyll
  - gem install html-proofer
  - gem install jekyll-redirect-from

script:
  - bash script/build.sh

sudo: false

env:
  global:
  - secure:
  #need to add the Travis encrypted data here

  
exclude: [vendor]

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  local_dir: ./_site
  target_branch: master
  on:
    branch: src
